### ISSUE TITLE
Import error when running from a fresh pip install

### ISSUE THREAD

**Issue by spacez320** [waynr/pyresume#95]
* PyResume Builder version: 0.1.0
* Python version: 2.7.14
* Operating System: Fedora 28 4.16.6-302.fc28.x86_64 x86_64 GNU/Linux

### Description

*Describe what you were trying to get done.*

Install pyresume and use it.

*Tell us what happened, what went wrong, and what you expected to happen.*

Any command that you try to invoke with pyresume seems to end in an ImportError stack-trace.

### What I Did

```
$ pip install --user pyresume
$ pyresume
Traceback (most recent call last):
  File "/home/matthew/.local/bin/pyresume", line 7, in <module>
    from pyresume.cli import main
ImportError: No module named cli
```

**Comment by waynr** [comment]
Hey thanks for the bug report! Right now I'm hiding from the rain under a
tarp in my hammock but I'll work on this tomorrow night and have a fix up
soon. In the mean time, you should be able to get it working if you run it
from source:

```
git clone git@github.com/waynr/pyresume; cd pyresume
pip install pipenv
pipenv install -e .
pipenv run pyresume -h
```

**Comment by waynr** [comment]
@spacez320 this should be fixed in the 0.1.1 release that will shortly be up on PyPi as long as the travis machinery for doing that kind of thing still works.

**Comment by waynr** [comment]
D'oh, I tagged the wrong branch. Fixing now.

**Comment by spacez320** [comment]
Thanks! Will give it a go and report back.

**Comment by waynr** [comment]
I'm actually about to push a 0.1.2 release, once I figure out why travis is failing to upload pypi packages.  Dev dependencies have been hiding the fact that the runtime dependencies are borked.

**Comment by waynr** [comment]
Okay, 0.1.2 was released by travis and seems to be working. The git repo also has a dockerfile that runs pyresume. And apparently I made a repo on docker hub: https://hub.docker.com/r/waynr/texlive-pyresume/ but I'm pretty sure the latter doesn't work at all.
